export type TargetTable = "companies" | "people";

export interface ProviderPreset {
  sourceKey: string;
  displayName: string;
  targetTable: TargetTable;
  columnMap: Record<string, string>;
}

export const BUILTIN_PROVIDERS: ProviderPreset[] = [
  {
    sourceKey: "aiark",
    displayName: "AI Ark",
    targetTable: "companies",
    columnMap: {
      "Company Name": "company_name",
      "Domain": "domain",
      "LinkedIn URL": "linkedin_url",
      "Website": "website_url",
      "Industry": "industry",
      "Employee Count": "employee_count",
      "City": "city",
      "State": "state",
      "Country": "country",
      "Phone": "phone",
      "Description": "description",
    },
  },
  {
    sourceKey: "apollo",
    displayName: "Apollo",
    targetTable: "companies",
    columnMap: {
      "Company": "company_name",
      "Company Name": "company_name",
      "Website": "website_url",
      "Company LinkedIn Url": "linkedin_url",
      "# Employees": "employee_count",
      "Industry": "industry",
      "City": "city",
      "State": "state",
      "Country": "country",
      "Corporate Phone": "phone",
    },
  },
  {
    sourceKey: "blitz",
    displayName: "Blitz",
    targetTable: "companies",
    columnMap: {
      "Company Name": "company_name",
      "Domain": "domain",
      "LinkedIn": "linkedin_url",
      "Website": "website_url",
      "Industry": "industry",
      "Employees": "employee_count",
      "City": "city",
      "State": "state",
      "Country": "country",
      "Phone": "phone",
    },
  },
  {
    sourceKey: "google-maps",
    displayName: "Google Maps",
    targetTable: "companies",
    columnMap: {
      "Title": "company_name",
      "Website": "website_url",
      "Phone": "phone",
      "City": "city",
      "State": "state",
      "Country": "country",
    },
  },
  {
    sourceKey: "clay",
    displayName: "Clay",
    targetTable: "companies",
    columnMap: {
      "Company Name": "company_name",
      "Domain": "domain",
      "LinkedIn URL": "linkedin_url",
      "Website": "website_url",
      "Industry": "industry",
      "Employees": "employee_count",
      "City": "city",
      "State": "state",
      "Country": "country",
    },
  },
  {
    sourceKey: "store-leads",
    displayName: "Store Leads",
    targetTable: "companies",
    columnMap: {
      "Name": "company_name",
      "Domain": "domain",
      "LinkedIn": "linkedin_url",
      "Website": "website_url",
      "Industry": "industry",
      "City": "city",
      "State": "state",
      "Country": "country",
      "Phone": "phone",
    },
  },
  {
    sourceKey: "builtwith",
    displayName: "BuiltWith",
    targetTable: "companies",
    columnMap: {
      "Domain": "domain",
      "Website": "website_url",
      "Country": "country",
    },
  },
  {
    sourceKey: "clutch",
    displayName: "Clutch",
    targetTable: "companies",
    columnMap: {
      "Company": "company_name",
      "Website": "website_url",
      "Location": "city",
      "Employees": "employee_count",
      "Description": "description",
    },
  },
  {
    sourceKey: "crunchbase",
    displayName: "Crunchbase",
    targetTable: "companies",
    columnMap: {
      "Organization Name": "company_name",
      "Website": "website_url",
      "LinkedIn": "linkedin_url",
      "Number of Employees": "employee_count",
      "Industry": "industry",
      "City": "city",
      "Country": "country",
      "Founded Year": "founded_year",
      "Description": "description",
    },
  },
  {
    sourceKey: "yelp",
    displayName: "Yelp",
    targetTable: "companies",
    columnMap: {
      "Business Name": "company_name",
      "Website": "website_url",
      "Phone": "phone",
      "City": "city",
      "State": "state",
      "Country": "country",
    },
  },
  {
    sourceKey: "salesnav",
    displayName: "Sales Navigator",
    targetTable: "people",
    columnMap: {
      "Full Name": "full_name",
      "First Name": "first_name",
      "Last Name": "last_name",
      "Job Title": "job_title",
      "Email": "email",
      "LinkedIn Profile URL": "linkedin_url",
      "Company": "company_name",
      "City": "city",
      "Country": "country",
    },
  },
  {
    sourceKey: "manual-csv",
    displayName: "Manual CSV",
    targetTable: "companies",
    columnMap: {},
  },
];

export const CANONICAL_SOURCE_KEYS = [
  "aiark",
  "blitz",
  "apollo",
  "google-maps",
  "store-leads",
  "builtwith",
  "clutch",
  "crunchbase",
  "yelp",
  "salesnav",
  "manual-csv",
] as const;

export const COMPANIES_FIELDS: string[] = [
  "company_name",
  "domain",
  "website_url",
  "linkedin_url",
  "industry",
  "city",
  "state",
  "country",
  "employee_count",
  "phone",
  "description",
  "founded_year",
  "revenue",
  "niche",
  "keywords",
  "technologies",
  "custom_data",
];

export const PEOPLE_FIELDS: string[] = [
  "first_name",
  "last_name",
  "full_name",
  "email",
  "phone",
  "job_title",
  "linkedin_url",
  "linkedin_username",
  "city",
  "state",
  "country",
  "company_name",
  "domain",
  "email_status",
  "phone_type",
  "custom_data",
  "source_id",
];

export const COLUMN_ALIASES: Record<string, string> = {
  website: "website_url",
  "website url": "website_url",
  url: "website_url",
  company: "company_name",
  "company name": "company_name",
  name: "company_name",
  organization: "company_name",
  linkedin: "linkedin_url",
  "linkedin url": "linkedin_url",
  employees: "employee_count",
  "employee count": "employee_count",
  size: "employee_count",
  "company size": "employee_count",
  headcount: "employee_count",
  "first name": "first_name",
  "last name": "last_name",
  "full name": "full_name",
  "job title": "job_title",
  title: "job_title",
  position: "job_title",
  "email address": "email",
  "phone number": "phone",
  founded: "founded_year",
  "year founded": "founded_year",
  vertical: "niche",
  sector: "industry",
};
